FoodStandardsAgency/register-a-food-business-front-end

- client/polyfills.js
- next.config.js
- src/__tests__/__snapshots__/summary-confirmation.test.js.snap
Don't merge until QA tests working on other browsers
> IE11 bugfix: add Object.keys polyfill

- src/server/connectors/config-db/config-db.connector.js
- src/server/connectors/config-db/config-db.connector.test.js
-Replace calls to unsupported Mongo distinct() function with find()
-Update associated tests
> replace distinct() with find()

- package.json
Merge release 4.2.0 to develop
> Merge release/4.2.0.0 to develop

- src/server/config.js
- src/server/connectors/address-lookup/addressSchema.js
- src/server/services/data-transform.service.js
Extract UPRN from API calls to lookup establishment & operator addresses
> extract UPRN from address lookup API calls

- package.json
Merge release 5.0.0 into develop
> Release 5.0.0

- pages_unit_tests/index.test.js
- src/components/FsaLayout.js
- src/components/SessionWrapper.js
- src/components/SessionWrapper.test.js
- src/server/services/browser-support.service.js
- src/server/services/browserSupport.service.test.js
- add isBrowserVersionVerified flag
- default isBrowserSupported to false
> Fix bug with isBrowserSupported flag

- pages/index.js
- src/__mocks__/storedStatusMock.json
- src/components/SessionWrapper.js
- src/server/connectors/config-db/config-db.connector.js
- src/server/connectors/config-db/config-db.connector.test.js
- src/server/routes/new.route.js
- src/server/routes/new.route.test.js
- Implement a way to easily retrieve any property from lcConfig
- State explicitly what LA user is about to register with on the index page
- Define associated tests
> Update index text

- src/components/BusinessTypeLookup.js
- Added comment to prevent clouflare caching next.js files
> Cloudflare cache 10/10/2019

- src/components/BusinessTypeLookup.js
- Update file to prevent caching
> Cloudflare cache fix 29/10/2019

- pages/establishment-address-manual.js
- pages/operator-address-manual.js
- src/components/SummaryTable.js
- src/components/SummaryTable.test.js
- src/server/config.js
- src/server/connectors/address-lookup/addressSchema.js
- src/server/services/data-transform.service.js
- src/server/services/schema.js
- src/server/services/validation.service.js
- Update address to include the UPRN correctly, instead of UDPRN
- Update the address to include the dependent locality
- Up manual address entry pages to include entry for dependent locality
> dependent locality and uprn 

- src/server/config.js
- src/server/connectors/address-lookup/address-lookup-api.connector.js
- src/server/connectors/address-lookup/address-lookup-api.connector.test.js
- Call postcoder API Standard service if Premium service returns zero addresses
- Update associated tests
> Fix no results for Northern Ireland addresses

- docs/contribution-guidelines/the-dynamic-form-path.md
> add information about partner details page to dynamic-form-path doc

- pages/establishment-address-select.js
- pages/operator-address-select.js
> Add space to manual address link.

- pages/_app.js
- src/components/CookieBanner.js
- src/components/PageTitles.js
- src/components/PageTitles.test.js
- src/components/SessionWrapper.js
- src/components/index.js
- Update cookie banner link colours
- Add page titles
> Accessibility updates

- src/server/services/path.service.js
- src/server/services/session-management.service.js
Emit log when clearing answers.
> Additional logging in Session Management

- src/components/BackAndLanguageBar.js
- src/components/FsaFooter.js
Add hrefs to ensure links can be tabbed to and operated by keyboard
> Change language links accessibility

- package.json
- polyfills.js
- src/components/BusinessTypeLookup.js
- src/components/DataListSection.js
- Fix data list options to allow screen reader to read them.
- Update accessible-autocomplete version to allow server side rendering
- Add specific IE polyfills
> Business type accessibility improvements

- package.json
- src/components/SelectListSection.js
- src/components/SelectListSection.test.js
- Revert to correct SelectInput GovUkReact component
- Default to the selected business type (I don't think this bit ever worked before, but does now)
> IE Business Type Select

- public/static/locales/cy.json
- public/static/locales/en.json
Updated links in en.json and cy.son to new feedback form
> Updated registration feedback links attempt 3

- pages/business-other-details.njk
Updated other details, changed page to be more inkeeping of other similar page. tested and working locally
> Updated other details

- components/EstablishmentDetails.njk
- pages/contact-local-authority.njk
- pages/establishment-address.njk
- pages/index.njk
- pages/la-established.njk
- pages/la-selector.njk
havent had chance to link up pages correctly or link buttons
> Added new pages

- src/server/connectors/local-authority-lookup/local-authority-lookup-api.connector.test.js
- src/server/controllers/find-local-authority.controller.test.js
- src/server/routes/find-local-authority.route.test.js
- src/server/services/local-authority.service.test.js
Unit tests added for these files.
Still need to add more to increase test case and coverage
> New unit tests for these files

- pages/layout.njk
- pages_unit_tests/index.test.js
- src/server/routes.js
Added GA4 google analytics tag
> Add GA4 google analytics tag

- pages/summary-confirmation.njk
- pages_unit_tests/summary-confirmation.test.js
added laguidance link and test
> added laguidancelink

- src/server/connectors/address-lookup/address-lookup-api.connector.js
- src/server/connectors/address-lookup/address-lookup-api.connector.test.js
- src/server/middleware/errorHandler.js
These errors have been edited to prevent triggering alerts
> ignoring certain errors

- components/BackButton.njk
- pages/la-established.njk
- pages/la-selector.njk
- pages_unit_tests/la-established.test.js
- pages_unit_tests/la-selector.test.js
- public/static/locales/cy.json
- public/static/locales/en.json
Wrong LA button added - need to add a UI test but on different repo
> Feature wrong la button

- pages/business-other-details.njk
removed old branch and changed wording
> Updated other details page after branching from develop

- src/server/services/data-transform.service.js
- src/server/services/data-transform.service.test.js
Fix issue with main partner contact details not being transformed for submission to API.
> Transform main partner to operator contact details for submit

- pages/registration-summary.njk
- src/server/services/data-transform.service.js
- src/server/services/data-transform.service.test.js
Update to birthdate display and transform only when required
> Update to birthdate display and transform only when required

- pages/registration-summary.njk
registration summary fixed and tested
> Reg summary fixed
